name: fatloss_app
description: "60-Day Veg Fat Loss Android & Mobile App with Firebase Auth & Cloud Firestore"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0D2821"
  adaptive_icon_foreground: "assets/icon.png"
